name: Auto YouTube Shorts from Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # Runs every 6 hours (optional)

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: sudo apt update -qq && sudo apt install -y ffmpeg fonts-dejavu-core

      - run: pip install pandas requests gtts moviepy==1.0.3 pillow numpy

      - run: python automation.py

      - uses: actions/upload-artifact@v4
        with:
          name: YouTube-Shorts-From-Sheet
          path: |
            *.mp4
            thumbnails/
